name: Build

on: [push]

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - uses: pnpm/action-setup@v2
            - uses: DimensionDev/github-token-action@latest
              with:
                  registry: true
            - run: pnpm install
            - run: pnpm run build
            - run: sh ./publish.sh
